services:
  postgres:
    image: postgres:17
    container_name: postgres-sql-movie
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_app
    ports:
      - "5433:5432"
    volumes:
      - postgres-movie:/var/lib/postgresql/data
    networks:
      - spring-demo
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres-movie:
    driver: local